// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnOFm5fVbB5NvPmjvBlHl14AIeToEj2jo',
    appId: '1:621710566726:web:6e880435fae6f7baf8b147',
    messagingSenderId: '621710566726',
    projectId: 'biogenius4-8b261',
    authDomain: 'biogenius4-8b261.firebaseapp.com',
    storageBucket: 'biogenius4-8b261.appspot.com',
    measurementId: 'G-ZKL5896PB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyOKbmXbN3ZcAqxaHYaMVXs3Yvc-X0I00',
    appId: '1:621710566726:android:05d2d2b385dabb8bf8b147',
    messagingSenderId: '621710566726',
    projectId: 'biogenius4-8b261',
    storageBucket: 'biogenius4-8b261.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACdpMV1Tt9np9tvMS2Txm_K0GncTSjuqQ',
    appId: '1:621710566726:ios:cde5810045bef820f8b147',
    messagingSenderId: '621710566726',
    projectId: 'biogenius4-8b261',
    storageBucket: 'biogenius4-8b261.appspot.com',
    iosBundleId: 'com.example.biogenius4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACdpMV1Tt9np9tvMS2Txm_K0GncTSjuqQ',
    appId: '1:621710566726:ios:cde5810045bef820f8b147',
    messagingSenderId: '621710566726',
    projectId: 'biogenius4-8b261',
    storageBucket: 'biogenius4-8b261.appspot.com',
    iosBundleId: 'com.example.biogenius4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnOFm5fVbB5NvPmjvBlHl14AIeToEj2jo',
    appId: '1:621710566726:web:e081f5faa5fbf707f8b147',
    messagingSenderId: '621710566726',
    projectId: 'biogenius4-8b261',
    authDomain: 'biogenius4-8b261.firebaseapp.com',
    storageBucket: 'biogenius4-8b261.appspot.com',
    measurementId: 'G-H8L2MNX7QC',
  );
}
